services:
  - type: web
    name: algorithm-visualizer-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn api:app --host 0.0.0.0 --port $PORT"
    
  - type: web
    name: algorithm-visualizer-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/dist" 